### ISSUE TITLE
No module named 'model.nms._ext.nms._nms'

### ISSUE THREAD

**Issue by momo1986** [frank-xwang/towards-universal-object-detection#1]
Hello, I have tried your script.
Thanks for sharing.
It reports the error when I run scripts "sh scripts/train_universal.sh " 

Error log is 

> File "universal_model.py", line 32, in <module>
>     from model.faster_rcnn.resnet_uni import resnet
>   File "/root/junyan/object_detection/towards-universal-object-detection/lib/model/faster_rcnn/resnet_uni.py", line 6, in <module>
>     from model.faster_rcnn.faster_rcnn_uni import _fasterRCNN
>   File "/root/junyan/object_detection/towards-universal-object-detection/lib/model/faster_rcnn/faster_rcnn_uni.py", line 10, in <module>
>     from model.rpn.rpn_universal import _RPN
>   File "/root/junyan/object_detection/towards-universal-object-detection/lib/model/rpn/rpn_universal.py", line 8, in <module>
>     from .proposal_layer import _ProposalLayer
>   File "/root/junyan/object_detection/towards-universal-object-detection/lib/model/rpn/proposal_layer.py", line 20, in <module>
>     from model.nms.nms_wrapper import nms
>   File "/root/junyan/object_detection/towards-universal-object-detection/lib/model/nms/nms_wrapper.py", line 10, in <module>
>     from model.nms.nms_gpu import nms_gpu
>   File "/root/junyan/object_detection/towards-universal-object-detection/lib/model/nms/nms_gpu.py", line 4, in <module>
>     from ._ext import nms
>   File "/root/junyan/object_detection/towards-universal-object-detection/lib/model/nms/_ext/nms/__init__.py", line 3, in <module>
>     from ._nms import lib as _lib, ffi as _ffi

Looks like path-setting problem, could you give some guide that the path could be searched correctly?

Thanks & Reagrds!
> ModuleNotFoundError: No module named 'model.nms._ext.nms._nms'

**Comment by frank-xwang** [comment]
Hi, this is cause by mismatched cuda version. You may need to make sure that the working environment is in cuda9.0/cuda9.1. Also, Pytorch need to be installed with cuda9.0/9.1 too.
