### ISSUE TITLE
USE module

### ISSUE THREAD

**Issue by roger-cv** [frank-xwang/towards-universal-object-detection#3]
Hey, this is a good work.
I have a simple question: could I adopt the USE module in image classification?

**Comment by frank-xwang** [comment]
Hi, thank you for your interest in our work. Yes, of course! You can simply add the USE module to the backbone network and use it as an attention module. However, we didn't explore the application of our USE module in the image classification task. Therefore, we may not be able to provide much support. It will be great to hear any updates on image classification tasks!
